In [2]:
import numpy as np

#  Q1 Create a NumPy array 'arr' of integers from 0 to 5
arr = np.arange(6)

# Print the data type of the array
print(arr)
print("Data type of the array:", arr.dtype)


[0 1 2 3 4 5]
Data type of the array: int32


In [3]:
#Q2 Create a NumPy array 'arr' check if its data type is float64.

#arr = np.array([1.5, 2.6, 3.7])
import numpy as np

# Create a NumPy array 'arr'
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type of 'arr' is float64
if arr.dtype == np.float64:
    print("The data type of 'arr' is float64.")
else:
    print("The data type of 'arr' is not float64.")


The data type of 'arr' is float64.


In [4]:
#Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
import numpy as np

# Create a NumPy array 'arr' with complex128 data type
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Print the array and its data type
print(arr)
print("Data type of the array:", arr.dtype)


[1.+2.j 3.+4.j 5.+6.j]
Data type of the array: complex128


In [5]:
# Convert an existing NumPy array 'arr' of integers to float32 data type.
import numpy as np

# Create a NumPy array 'arr' of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the original and the converted arrays
print("Original array:", arr)
print("Converted array:", arr_float32)
print("Data type of the converted array:", arr_float32.dtype)


Original array: [1 2 3 4 5]
Converted array: [1. 2. 3. 4. 5.]
Data type of the converted array: float32


In [6]:
# Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
import numpy as np

# Create a NumPy array 'arr' with float64 data type
arr = np.array([1.123456789, 2.987654321, 3.1415926535], dtype=np.float64)

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the original and the converted arrays
print("Original array:", arr)
print("Converted array with reduced precision:", arr_float32)
print("Data type of the converted array:", arr_float32.dtype)


Original array: [1.12345679 2.98765432 3.14159265]
Converted array with reduced precision: [1.1234568 2.9876542 3.1415927]
Data type of the converted array: float32


In [7]:
#7Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.
import numpy as np

def array_attributes(arr):
    # Get the shape of the array
    shape = arr.shape
    # Get the size of the array
    size = arr.size
    # Get the data type of the array
    dtype = arr.dtype
    
    return shape, size, dtype

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)



Shape: (2, 3)
Size: 6
Data type: int32


In [3]:
import numpy as np
#Create a function array_dimension that takes a NumPy array as input and returns its dimensionality
def array_dimension(arr):
    # Get the dimensionality of the array
    return arr.ndim

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimensionality = array_dimension(arr)
print("Dimensionality of the array:", dimensionality)


Dimensionality of the array: 2


In [4]:
#Design a function item_size_info that takes a NumPy array as input and returns the item size and the totalsize in bytes.


def item_size_info(arr):
    # Get the size of one element in the array (in bytes)
    item_size = arr.itemsize
    
    # Get the total size of the array (in bytes)
    total_size = arr.nbytes
    
    return item_size, total_size

# Example usage:
arr = np.array([1, 2, 3, 4, 5])
item_size, total_size = item_size_info(arr)
print(f"Item size: {item_size} bytes")
print(f"Total size: {total_size} bytes")


Item size: 4 bytes
Total size: 20 bytes


In [5]:
#9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array
import numpy as np

def array_strides(arr):
    # Return the strides of the array
    return arr.strides

# Example usage:
arr = np.array([[1, 2, 3], [4, 5, 6]])
strides = array_strides(arr)
print(f"Strides: {strides}")


Strides: (12, 4)


arr.strides: This attribute returns a tuple of integers that indicate how many bytes to skip in memory when moving to the next element along each dimension of the array.

In [6]:
#10Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements


def create_zeros_array(n):
    # Create and return a NumPy array of zeros with n elements
    return np.zeros(n)

# Example usage:
n = 5
zeros_array = create_zeros_array(n)
print(zeros_array)


[0. 0. 0. 0. 0.]


np.zeros(n): This function generates a NumPy array of length n, filled with zeros.
This function will return an array of zeros of any length you specify with n.

In [7]:
#11 Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
import numpy as np

def create_ones_matrix(rows, cols):
    # Create and return a 2D NumPy array of ones with shape (rows, cols)
    return np.ones((rows, cols))

# Example usage:
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(ones_matrix)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


np.ones((rows, cols)): This creates a 2D NumPy array of shape (rows, cols) filled with ones.
This function will generate a matrix of any size filled with ones based on the input values of rows and cols.

In [8]:
#12Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.


def generate_range_array(start, stop, step):
    # Create and return a NumPy array with the specified range
    return np.arange(start, stop, step)

# Example usage:
start = 1
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(range_array)


[1 3 5 7 9]


np.arange(start, stop, step): This function generates a NumPy array starting from start, going up to (but not including) stop, with a step size of step.

In [13]:
#14 Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
#(inclusive).

import numpy as np

def generate_linear_space(start, stop, num):
    # Create and return a NumPy array with num equally spaced values between start and stop
    return np.linspace(start, stop, num)

# Example usage:
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print(linear_space_array)


[0.   0.25 0.5  0.75 1.  ]


np.linspace(start, stop, num): This function generates num equally spaced values between start and stop (both inclusive).

In [12]:
#15Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
#identity matrix of size `n x n` using `numpy.eye`.


def create_identity_matrix(n):
    # Create and return an identity matrix of size n x n
    return np.eye(n)

# Example usage:
n = 4
identity_matrix = create_identity_matrix(n)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


np.eye(n): This function creates a 2D square identity matrix of size n x n, where the diagonal elements are 1 and the off-diagonal elements are 0.

In [11]:
#16Write a function that takes a Python list and converts it into a NumPy array.

def list_to_numpy_array(py_list):
    # Convert the Python list to a NumPy array
    return np.array(py_list)

# Example usage:
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)
print(numpy_array)


[1 2 3 4 5]


In [14]:
#17. Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data.
import numpy as np

# Original array
original_array = np.array([1, 2, 3, 4, 5])

# Create a view of the array
new_array_view = original_array.view()

# Print both arrays
print("Original array:", original_array)
print("New array (view):", new_array_view)


Original array: [1 2 3 4 5]
New array (view): [1 2 3 4 5]


In [15]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(concatenate_arrays(arr1, arr2, axis=0))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [16]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

# Concatenate horizontally (axis=1)
result = np.concatenate((arr1, arr2.T), axis=1)

print(result)


[[1 2 5]
 [3 4 6]]


In [17]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list.
def vertical_stack(arrays_list):
    return np.vstack(arrays_list)

# Example usage
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(vertical_stack([arr1, arr2]))


[[1 2 3]
 [4 5 6]]


In [18]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

# Example usage
print(create_range_array(1, 10, 2))


[1 3 5 7 9]


In [19]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
def generate_equally_spaced():
    return np.linspace(0, 1, 10)

# Example usage
print(generate_equally_spaced())


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [20]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
def generate_log_space():
    return np.logspace(0, 3, 5)

# Example usage
print(generate_log_space())


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [21]:
#24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns,
#where the values are random integers between 1 and 100
import pandas as pd

def create_dataframe():
    data = np.random.randint(1, 101, size=(5, 3))
    df = pd.DataFrame(data, columns=['A', 'B', 'C'])
    return df

# Example usage
print(create_dataframe())


    A   B   C
0  78  70  38
1  43  32  47
2  86  45   7
3  63  99  20
4  45  35  37


In [24]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. 
#Use NumPy operations within the Pandas DataFrame.
import pandas as pd
import numpy as np

def replace_negatives(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage
data = {'A': [1, -2, 3, -4], 'B': [5, 6, -7, 8]}
df = pd.DataFrame(data)
print(replace_negatives(df, 'A'))


   A  B
0  1  5
1  0  6
2  3 -7
3  0  8


In [25]:
#26. Access the 3rd element from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5])
third_element = arr[2]
print(third_element)


3


In [26]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = arr_2d[1, 2]
print(element)


6


In [27]:
#28 . Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
filtered_elements = arr[arr > 5]
print(filtered_elements)


[ 8 10  7]


In [30]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1,2,3,4,5,6,7,8,9])
sliced_array = arr[2:6]
print(sliced_array)


[3 4 5 6]


In [29]:
#30. Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print(sub_array)


[[2 3]
 [5 6]]


In [31]:
#31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
def extract_elements(arr, indices):
    return arr[indices]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([0, 2])
print(extract_elements(arr_2d, indices))


[[1 2 3]
 [7 8 9]]


In [32]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
def filter_elements(arr, threshold):
    return arr[arr > threshold]

arr = np.array([3, 8, 2, 10, 5, 7])
print(filter_elements(arr, 5))


[ 8 10  7]


In [33]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension
def extract_from_3d(arr, idx1, idx2, idx3):
    return arr[idx1, idx2, idx3]

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
idx1 = np.array([0, 1])
idx2 = np.array([0, 1])
idx3 = np.array([1, 0])
print(extract_from_3d(arr_3d, idx1, idx2, idx3))


[2 7]


In [34]:
#34. Write a NumPy function that returns elements from an array where two conditions are satisfied using boolean indexing.
def filter_two_conditions(arr, cond1, cond2):
    return arr[(arr > cond1) & (arr < cond2)]

arr = np.array([3, 8, 2, 10, 5, 7])
print(filter_two_conditions(arr, 4, 9))


[8 5 7]


In [35]:
#35 Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays
def extract_using_indices(arr, row_indices, col_indices):
    return arr[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([2, 1, 0])
print(extract_using_indices(arr_2d, row_indices, col_indices))


[3 5 7]


In [36]:
#36 Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr += 5
print(arr)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [37]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]])

result = arr2 * arr1.T
print(result)


[[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [38]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([[5, 6, 7], [8, 9, 10], [11, 12, 13], [14, 15, 16]])

result = arr2 + arr1.reshape(-1, 1)
print(result)


[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [39]:
#39 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
arr1 = np.array([[1], [2], [3]])
arr2 = np.array([[4, 5, 6]])

result = arr1 + arr2
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [40]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])

# Broadcasting not possible directly, so we modify shapes if needed
arr2_broadcast = np.hstack((arr2, np.zeros((2, 1))))
result = arr1 * arr2_broadcast

print(result)


[[ 7. 16.  0.]
 [36. 50.  0.]]


In [41]:
#41. Calculate column-wise mean for the given array.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_mean = np.mean(arr, axis=0)
print(column_mean)


[4. 5. 6.]


In [42]:
#42. Find the maximum value in each row of the given array.
row_max = np.max(arr, axis=1)
print(row_max)


[3 6 9]


In [43]:
#43. For the given array, find indices of maximum value in each column.
col_max_indices = np.argmax(arr, axis=0)
print(col_max_indices)


[2 2 2]


In [44]:
#44. For the given array, apply a custom function to calculate moving sum along rows.
def moving_sum(arr):
    return np.cumsum(arr, axis=1)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(moving_sum(arr))


[[ 1  3  6]
 [ 4  9 15]]


In [45]:
#45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
is_even = np.all(arr % 2 == 0, axis=0)
print(is_even)


[False False False]


In [46]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the reshaped matrix.
def reshape_array(arr, m, n):
    return arr.reshape(m, n)

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_matrix = reshape_array(arr, 2, 3)
print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


In [47]:
#47. Create a function that takes a matrix as input and returns the flattened array.
def flatten_matrix(matrix):
    return matrix.flatten()

matrix = np.array([[1, 2], [3, 4]])
flattened = flatten_matrix(matrix)
print(flattened)


[1 2 3 4]


In [48]:
#48. Write a function that concatenates two given arrays along a specified axis.
def concatenate_arrays(arr1, arr2, axis=0):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

result = concatenate_arrays(arr1, arr2, axis=1)
print(result)


[[1 2 5 6]
 [3 4 7 8]]


In [49]:
#49 . Create a function that splits an array into multiple sub-arrays along a specified axis.
def split_array(arr, indices_or_sections, axis=0):
    return np.split(arr, indices_or_sections, axis=axis)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
split_result = split_array(arr, 2, axis=1)
print(split_result)


[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [50]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices
def insert_delete_elements(arr, insert_indices, insert_values, delete_indices):
    arr = np.insert(arr, insert_indices, insert_values)
    arr = np.delete(arr, delete_indices)
    return arr

arr = np.array([1, 2, 3, 4, 5])
inserted_deleted = insert_delete_elements(arr, [2, 4], [10, 11], [1, 3])
print(inserted_deleted)


[ 1 10  4 11  5]


In [51]:
#51. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2.
arr1 = np.random.randint(1, 11, size=10)
arr2 = np.arange(1, 11)
result = arr1 + arr2
print(result)


[ 4  6 11  8  7 15 16 12 11 19]


In [52]:
#52. Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise.
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print(result)


[ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [53]:
#53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2.
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)
result = arr1 * arr2
print(result)


[ 6 14 15 32 20]


In [54]:
#54. Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2.
arr1 = np.arange(2, 11, 2)
arr2 = np.arange(1, 6)
result = arr1 / arr2
print(result)


[2. 2. 2. 2. 2.]


In [55]:
#55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.
arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result = arr1 ** arr2
print(result)


[ 1 16 27 16  5]


In [56]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
def count_substring(arr, substring):
    return np.char.count(arr, substring)

arr = np.array(['apple', 'banana', 'apple', 'grape'])
substring_count = count_substring(arr, 'apple')
print(substring_count)


[1 0 1 0]


In [57]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.
def extract_uppercase(arr):
    return np.char.find(arr, np.char.upper(arr))

arr = np.array(['Hello', 'World', 'OpenAI'])
uppercase = extract_uppercase(arr)
print(uppercase)


[-1 -1 -1]


In [ ]:
#58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

arr = np.array(['apple', 'banana', 'grape'])
replaced = replace_substring(arr, 'apple', 'orange')
print(replaced)


In [59]:
#59. Write a function that concatenates strings in a NumPy array element-wise.
def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'Open'])
arr2 = np.array([' World', ' asd'])
concatenated = concatenate_strings(arr1, arr2)
print(concatenated)


['Hello World' 'Open asd']


In [60]:
#60. Write a function that finds the length of the longest string in a NumPy array.
def longest_string_length(arr):
    return np.max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'pineapple'])
max_length = longest_string_length(arr)
print(max_length)


9


In [61]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
arr = np.random.randint(1, 1001, size=100)
mean = np.mean(arr)
median = np.median(arr)
variance = np.var(arr)
std_dev = np.std(arr)

print(f"Mean: {mean}, Median: {median}, Variance: {variance}, Standard Deviation: {std_dev}")


Mean: 505.21, Median: 489.0, Variance: 75904.46590000001, Standard Deviation: 275.5076512549153


In [62]:
#62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
arr = np.random.randint(1, 101, size=50)
percentile_25 = np.percentile(arr, 25)
percentile_75 = np.percentile(arr, 75)

print(f"25th percentile: {percentile_25}, 75th percentile: {percentile_75}")


25th percentile: 24.0, 75th percentile: 71.75


In [63]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

arr1 = np.random.randint(1, 100, size=50)
arr2 = np.random.randint(1, 100, size=50)
correlation = np.corrcoef(arr1, arr2)

print(correlation)


[[ 1.         -0.25186392]
 [-0.25186392  1.        ]]


In [64]:
#64. Create two matrices and perform matrix multiplication using NumPy's dot function.
matrix1 = np.random.randint(1, 10, size=(3, 2))
matrix2 = np.random.randint(1, 10, size=(2, 3))
result = np.dot(matrix1, matrix2)

print(result)


[[92 93 48]
 [16 19  9]
 [56 60 30]]


In [ ]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
arr = np.random.randint(10, 1001, size=50)
percentile_10 = np.percentile(arr, 10)
percentile_50 = np.percentile(arr, 50)
percentile_90 = np.percentile(arr, 90)
q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)

print(f"10th: {percentile_10}, 50th (Median): {percentile_50}, 90th: {percentile_90}, Q1: {q1}, Q3: {q3}")


In [65]:
#66. Create a NumPy array of integers and find the index of a specific element.
arr = np.array([10, 20, 30, 40, 50])
index = np.where(arr == 30)

print(index)


(array([2], dtype=int64),)


In [66]:
#67. Generate a random NumPy array and sort it in ascending order.
arr = np.random.randint(1, 101, size=10)
sorted_arr = np.sort(arr)

print(sorted_arr)


[ 7 20 21 25 33 35 70 75 86 99]


In [67]:
#68. Filter elements >20 in the given NumPy array.
arr = np.array([5, 25, 15, 30, 50, 10])
filtered = arr[arr > 20]

print(filtered)


[25 30 50]


In [68]:
#69. Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([3, 8, 12, 15, 20])
filtered = arr[arr % 3 == 0]

print(filtered)


[ 3 12 15]


In [69]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])
filtered = arr[(arr >= 20) & (arr <= 40)]

print(filtered)


[20 30 40]


In [70]:
#71. For the given NumPy array, check its byte order using the dtype attribute byteorder.
arr = np.array([1, 2, 3], dtype=np.int32)
byte_order = arr.dtype.byteorder

print(byte_order)



=


In [71]:
#72. For the given NumPy array, perform byte swapping in place using byteswap().
arr = np.array([1, 256, 65536], dtype=np.int32)
arr.byteswap(inplace=True)

print(arr)


[16777216    65536      256]


In [72]:
#73. For the given NumPy array, swap its byte order without modifying the original array using newbyteorder().
arr = np.array([1, 256, 65536], dtype=np.int32)
swapped_arr = arr.newbyteorder()

print(swapped_arr)


[16777216    65536      256]


In [73]:
#74  For the given NumPy array, swap its byte order conditionally based on system endianness using newbyteorder().
arr = np.array([1, 256, 65536], dtype=np.int32)
if arr.dtype.byteorder == '=':  # Native endianness
    swapped_arr = arr.newbyteorder()

print(swapped_arr)


[16777216    65536      256]


In [74]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using dtype attribute byteorder.
arr = np.array([1, 256, 65536], dtype=np.int32)
is_swap_needed = arr.dtype.byteorder != '='

print(is_swap_needed)


False


In [ ]:
#76. Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named copy_arr and modify an element in copy_arr. Check if modifying copy_arr affects arr1.
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100

print(arr1)  # Original array
print(copy_arr)  # Modified copy


In [75]:
#77. Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from the matrix. Modify an element in view_slice and observe if it changes the original matrix.
matrix = np.random.randint(1, 10, size=(3, 3))
view_slice = matrix[0:2, 0:2]
view_slice[0, 0] = 100

print(matrix)  # The original matrix will be modified


[[100   6   5]
 [  7   3   6]
 [  1   8   9]]


In [76]:
#78. Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[0:2, :]
view_b += 5

print(array_a)  # The original array will be modified


[[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]


In [77]:
#79. Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify an element in reshaped_view and check if it reflects changes in the original orig_array.
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 100

print(orig_array)  # The original array will be modified


[[100   2   3   4]
 [  5   6   7   8]]


In [78]:
#80. Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data.
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 100

print(data)  # Original data will remain unchanged


[[9 2 6 5]
 [1 9 8 4]
 [4 4 8 9]]


In [80]:
#80. Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data.
data = np.random.randint(1, 10, size=(3, 4))
data_copy = data[data > 5].copy()  # Create a copy of elements greater than 5
data_copy[0] = 100  # Modify an element in the copy

print("Original Data:")
print(data)  # The original data will remain unchanged
print("\nModified Data Copy:")
print(data_copy)  # The modified copy


Original Data:
[[9 3 1 4]
 [3 8 8 3]
 [5 9 7 4]]

Modified Data Copy:
[100   8   8   9   7]


In [79]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between the
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

addition_result = A + B
subtraction_result = A - B

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition of A and B:")
print(addition_result)
print("\nSubtraction of A and B:")
print(subtraction_result)


Matrix A:
[[6 9 9]
 [9 7 9]
 [3 5 9]]

Matrix B:
[[1 3 2]
 [9 7 4]
 [7 5 5]]

Addition of A and B:
[[ 7 12 11]
 [18 14 13]
 [10 10 14]]

Subtraction of A and B:
[[ 5  6  7]
 [ 0  0  5]
 [-4  0  4]]


In [81]:
#82. Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.
C = np.random.randint(1, 10, size=(3, 2))
D = np.random.randint(1, 10, size=(2, 4))

matrix_multiplication_result = np.dot(C, D)

print("Matrix C:")
print(C)
print("\nMatrix D:")
print(D)
print("\nMatrix Multiplication Result (C * D):")
print(matrix_multiplication_result)


Matrix C:
[[4 6]
 [8 5]
 [9 3]]

Matrix D:
[[3 1 2 3]
 [3 1 8 8]]

Matrix Multiplication Result (C * D):
[[30 10 56 60]
 [39 13 56 64]
 [36 12 42 51]]


In [82]:
#83. Create a matrix E and find its transpose.
E = np.random.randint(1, 10, size=(3, 3))

transpose_E = E.T

print("Matrix E:")
print(E)
print("\nTranspose of Matrix E:")
print(transpose_E)


Matrix E:
[[8 6 8]
 [4 8 4]
 [4 4 6]]

Transpose of Matrix E:
[[8 4 4]
 [6 8 4]
 [8 4 6]]


In [83]:
#84. Generate a square matrix F and compute its determinant.
F = np.random.randint(1, 10, size=(3, 3))

determinant_F = np.linalg.det(F)

print("Matrix F:")
print(F)
print("\nDeterminant of Matrix F:")
print(determinant_F)


Matrix F:
[[1 4 8]
 [6 6 6]
 [2 6 2]]

Determinant of Matrix F:
167.99999999999997


In [84]:
#85. Create a square matrix G and find its inverse.
G = np.random.randint(1, 10, size=(3, 3))

# Check if the matrix is invertible (determinant is not zero)
if np.linalg.det(G) != 0:
    inverse_G = np.linalg.inv(G)
    print("Matrix G:")
    print(G)
    print("\nInverse of Matrix G:")
    print(inverse_G)
else:
    print("Matrix G is singular and does not have an inverse.")


Matrix G:
[[4 7 8]
 [9 6 2]
 [1 5 2]]

Inverse of Matrix G:
[[ 0.00961538  0.125      -0.16346154]
 [-0.07692308  0.          0.30769231]
 [ 0.1875     -0.0625     -0.1875    ]]
